//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocol/cs_enum.proto
namespace protocol.cs_enum
{
    [global::ProtoBuf.ProtoContract(Name=@"ENUM_CMD")]
    public enum ENUM_CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_LOGIN_REQ", Value=0)]
      CS_LOGIN_REQ = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_LOGIN_RES", Value=1)]
      CS_LOGIN_RES = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_SEND_MESSAGE_REQ", Value=4)]
      CS_SEND_MESSAGE_REQ = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_SEND_MESSAGE_RES", Value=5)]
      CS_SEND_MESSAGE_RES = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_MESSAGE_NOTIFY", Value=6)]
      CS_MESSAGE_NOTIFY = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_CHUNKS_ENTER_LEVAE_VIEW_REQ", Value=7)]
      CS_CHUNKS_ENTER_LEVAE_VIEW_REQ = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_CHUNKS_ENTER_LEAVE_VIEW_RES", Value=8)]
      CS_CHUNKS_ENTER_LEAVE_VIEW_RES = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_ADD_BLOCK_REQ", Value=9)]
      CS_ADD_BLOCK_REQ = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_ADD_BLOCK_RES", Value=10)]
      CS_ADD_BLOCK_RES = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_ADD_BLOCK_NOTIFY", Value=11)]
      CS_ADD_BLOCK_NOTIFY = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_DELETE_BLOCK_REQ", Value=12)]
      CS_DELETE_BLOCK_REQ = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_DELETE_BLOCK_RES", Value=13)]
      CS_DELETE_BLOCK_RES = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_DELETE_BLOCK_NOTIFY", Value=14)]
      CS_DELETE_BLOCK_NOTIFY = 14
    }
  
}