//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protocol/cs_theircraft.proto
namespace protocol.cs_theircraft
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSBlockAttrs")]
  public partial class CSBlockAttrs : global::ProtoBuf.IExtensible
  {
    public CSBlockAttrs() {}
    
    private CSVector3Int _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CSVector3Int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private CSBlockOrientation _orient = CSBlockOrientation.Default;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"orient", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(CSBlockOrientation.Default)]
    public CSBlockOrientation orient
    {
      get { return _orient; }
      set { _orient = value; }
    }
    private CSVector3Int _depentPos = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"depentPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CSVector3Int depentPos
    {
      get { return _depentPos; }
      set { _depentPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSVector2Int")]
  public partial class CSVector2Int : global::ProtoBuf.IExtensible
  {
    public CSVector2Int() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSVector3")]
  public partial class CSVector3 : global::ProtoBuf.IExtensible
  {
    public CSVector3() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSVector3Int")]
  public partial class CSVector3Int : global::ProtoBuf.IExtensible
  {
    public CSVector3Int() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSBlock")]
  public partial class CSBlock : global::ProtoBuf.IExtensible
  {
    public CSBlock() {}
    
    private CSVector3Int _position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CSVector3Int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private CSBlockType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public CSBlockType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private CSBlockOrientation _orient = CSBlockOrientation.Default;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"orient", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(CSBlockOrientation.Default)]
    public CSBlockOrientation orient
    {
      get { return _orient; }
      set { _orient = value; }
    }
    private CSVector3Int _depentPos = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"depentPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CSVector3Int depentPos
    {
      get { return _depentPos; }
      set { _depentPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSItem")]
  public partial class CSItem : global::ProtoBuf.IExtensible
  {
    public CSItem() {}
    
    private CSBlockType _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public CSBlockType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private uint _Count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Count
    {
      get { return _Count; }
      set { _Count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSPlayer")]
  public partial class CSPlayer : global::ProtoBuf.IExtensible
  {
    public CSPlayer() {}
    
    private uint _PlayerID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PlayerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PlayerID
    {
      get { return _PlayerID; }
      set { _PlayerID = value; }
    }
    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private CSVector3 _Position = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CSVector3 Position
    {
      get { return _Position; }
      set { _Position = value; }
    }
    private CSVector3 _Rotation = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CSVector3 Rotation
    {
      get { return _Rotation; }
      set { _Rotation = value; }
    }
    private uint _SelectIndex = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"SelectIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint SelectIndex
    {
      get { return _SelectIndex; }
      set { _SelectIndex = value; }
    }
    private readonly global::System.Collections.Generic.List<CSItem> _SelectItems = new global::System.Collections.Generic.List<CSItem>();
    [global::ProtoBuf.ProtoMember(6, Name=@"SelectItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSItem> SelectItems
    {
      get { return _SelectItems; }
    }
  
    private readonly global::System.Collections.Generic.List<CSItem> _BagItems = new global::System.Collections.Generic.List<CSItem>();
    [global::ProtoBuf.ProtoMember(7, Name=@"BagItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSItem> BagItems
    {
      get { return _BagItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSChunk")]
  public partial class CSChunk : global::ProtoBuf.IExtensible
  {
    public CSChunk() {}
    
    private CSVector2Int _Position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CSVector2Int Position
    {
      get { return _Position; }
      set { _Position = value; }
    }
    private readonly global::System.Collections.Generic.List<CSBlock> _Blocks = new global::System.Collections.Generic.List<CSBlock>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Blocks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSBlock> Blocks
    {
      get { return _Blocks; }
    }
  
    private byte[] _BlocksInBytes = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"BlocksInBytes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] BlocksInBytes
    {
      get { return _BlocksInBytes; }
      set { _BlocksInBytes = value; }
    }
    private readonly global::System.Collections.Generic.List<CSPlayer> _Players = new global::System.Collections.Generic.List<CSPlayer>();
    [global::ProtoBuf.ProtoMember(4, Name=@"Players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSPlayer> Players
    {
      get { return _Players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSRegisterReq")]
  public partial class CSRegisterReq : global::ProtoBuf.IExtensible
  {
    public CSRegisterReq() {}
    
    private string _Account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSRegisterRes")]
  public partial class CSRegisterRes : global::ProtoBuf.IExtensible
  {
    public CSRegisterRes() {}
    
    private int _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLoginReq")]
  public partial class CSLoginReq : global::ProtoBuf.IExtensible
  {
    public CSLoginReq() {}
    
    private string _Account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLoginRes")]
  public partial class CSLoginRes : global::ProtoBuf.IExtensible
  {
    public CSLoginRes() {}
    
    private int _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private CSPlayer _PlayerData = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PlayerData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CSPlayer PlayerData
    {
      get { return _PlayerData; }
      set { _PlayerData = value; }
    }
    private readonly global::System.Collections.Generic.List<CSBlockAttrs> _BlockAttrs = new global::System.Collections.Generic.List<CSBlockAttrs>();
    [global::ProtoBuf.ProtoMember(4, Name=@"BlockAttrs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSBlockAttrs> BlockAttrs
    {
      get { return _BlockAttrs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSSendMessageReq")]
  public partial class CSSendMessageReq : global::ProtoBuf.IExtensible
  {
    public CSSendMessageReq() {}
    
    private string _Content;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSSendMessageRes")]
  public partial class CSSendMessageRes : global::ProtoBuf.IExtensible
  {
    public CSSendMessageRes() {}
    
    private int _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSMessageNotify")]
  public partial class CSMessageNotify : global::ProtoBuf.IExtensible
  {
    public CSMessageNotify() {}
    
    private string _Name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _Content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSChunksEnterLeaveViewReq")]
  public partial class CSChunksEnterLeaveViewReq : global::ProtoBuf.IExtensible
  {
    public CSChunksEnterLeaveViewReq() {}
    
    private readonly global::System.Collections.Generic.List<CSVector2Int> _EnterViewChunks = new global::System.Collections.Generic.List<CSVector2Int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"EnterViewChunks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSVector2Int> EnterViewChunks
    {
      get { return _EnterViewChunks; }
    }
  
    private readonly global::System.Collections.Generic.List<CSVector2Int> _LeaveViewChunks = new global::System.Collections.Generic.List<CSVector2Int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"LeaveViewChunks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSVector2Int> LeaveViewChunks
    {
      get { return _LeaveViewChunks; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSChunksEnterLeaveViewRes")]
  public partial class CSChunksEnterLeaveViewRes : global::ProtoBuf.IExtensible
  {
    public CSChunksEnterLeaveViewRes() {}
    
    private int _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private readonly global::System.Collections.Generic.List<CSChunk> _EnterViewChunks = new global::System.Collections.Generic.List<CSChunk>();
    [global::ProtoBuf.ProtoMember(2, Name=@"EnterViewChunks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSChunk> EnterViewChunks
    {
      get { return _EnterViewChunks; }
    }
  
    private readonly global::System.Collections.Generic.List<CSVector2Int> _LeaveViewChunks = new global::System.Collections.Generic.List<CSVector2Int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"LeaveViewChunks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSVector2Int> LeaveViewChunks
    {
      get { return _LeaveViewChunks; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSAddBlockReq")]
  public partial class CSAddBlockReq : global::ProtoBuf.IExtensible
  {
    public CSAddBlockReq() {}
    
    private CSBlock _block;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"block", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CSBlock block
    {
      get { return _block; }
      set { _block = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSAddBlockRes")]
  public partial class CSAddBlockRes : global::ProtoBuf.IExtensible
  {
    public CSAddBlockRes() {}
    
    private int _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private CSBlock _block;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"block", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CSBlock block
    {
      get { return _block; }
      set { _block = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSAddBlockNotify")]
  public partial class CSAddBlockNotify : global::ProtoBuf.IExtensible
  {
    public CSAddBlockNotify() {}
    
    private CSBlock _block;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"block", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CSBlock block
    {
      get { return _block; }
      set { _block = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSDeleteBlockReq")]
  public partial class CSDeleteBlockReq : global::ProtoBuf.IExtensible
  {
    public CSDeleteBlockReq() {}
    
    private CSVector3Int _position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CSVector3Int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSDeleteBlockRes")]
  public partial class CSDeleteBlockRes : global::ProtoBuf.IExtensible
  {
    public CSDeleteBlockRes() {}
    
    private int _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private readonly global::System.Collections.Generic.List<CSVector3Int> _position = new global::System.Collections.Generic.List<CSVector3Int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSVector3Int> position
    {
      get { return _position; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSDeleteBlockNotify")]
  public partial class CSDeleteBlockNotify : global::ProtoBuf.IExtensible
  {
    public CSDeleteBlockNotify() {}
    
    private readonly global::System.Collections.Generic.List<CSVector3Int> _position = new global::System.Collections.Generic.List<CSVector3Int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSVector3Int> position
    {
      get { return _position; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSHeroMoveReq")]
  public partial class CSHeroMoveReq : global::ProtoBuf.IExtensible
  {
    public CSHeroMoveReq() {}
    
    private CSVector3 _Position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CSVector3 Position
    {
      get { return _Position; }
      set { _Position = value; }
    }
    private CSVector3 _Rotation;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CSVector3 Rotation
    {
      get { return _Rotation; }
      set { _Rotation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSHeroMoveRes")]
  public partial class CSHeroMoveRes : global::ProtoBuf.IExtensible
  {
    public CSHeroMoveRes() {}
    
    private int _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSPlayerMoveNotify")]
  public partial class CSPlayerMoveNotify : global::ProtoBuf.IExtensible
  {
    public CSPlayerMoveNotify() {}
    
    private uint _PlayerID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PlayerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PlayerID
    {
      get { return _PlayerID; }
      set { _PlayerID = value; }
    }
    private CSVector3 _Position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CSVector3 Position
    {
      get { return _Position; }
      set { _Position = value; }
    }
    private CSVector3 _Rotation;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CSVector3 Rotation
    {
      get { return _Rotation; }
      set { _Rotation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSPlayerEnterViewNotify")]
  public partial class CSPlayerEnterViewNotify : global::ProtoBuf.IExtensible
  {
    public CSPlayerEnterViewNotify() {}
    
    private CSPlayer _PlayerData;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PlayerData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CSPlayer PlayerData
    {
      get { return _PlayerData; }
      set { _PlayerData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSPlayerLeaveViewNotify")]
  public partial class CSPlayerLeaveViewNotify : global::ProtoBuf.IExtensible
  {
    public CSPlayerLeaveViewNotify() {}
    
    private uint _PlayerID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PlayerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PlayerID
    {
      get { return _PlayerID; }
      set { _PlayerID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSHeroChangeSelectIndexReq")]
  public partial class CSHeroChangeSelectIndexReq : global::ProtoBuf.IExtensible
  {
    public CSHeroChangeSelectIndexReq() {}
    
    private uint _Index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSHeroChangeSelectItemReq")]
  public partial class CSHeroChangeSelectItemReq : global::ProtoBuf.IExtensible
  {
    public CSHeroChangeSelectItemReq() {}
    
    private uint _Index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private CSBlockType _Item;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public CSBlockType Item
    {
      get { return _Item; }
      set { _Item = value; }
    }
    private uint _Count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Count
    {
      get { return _Count; }
      set { _Count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlobChunkData")]
  public partial class BlobChunkData : global::ProtoBuf.IExtensible
  {
    public BlobChunkData() {}
    
    private readonly global::System.Collections.Generic.List<CSBlock> _BlockList = new global::System.Collections.Generic.List<CSBlock>();
    [global::ProtoBuf.ProtoMember(1, Name=@"BlockList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CSBlock> BlockList
    {
      get { return _BlockList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CSBlockType")]
    public enum CSBlockType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"None", Value=0)]
      None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Dirt", Value=1)]
      Dirt = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GrassBlock", Value=2)]
      GrassBlock = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Tnt", Value=3)]
      Tnt = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Brick", Value=4)]
      Brick = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Furnace", Value=5)]
      Furnace = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HayBlock", Value=6)]
      HayBlock = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JungleLeaves", Value=7)]
      JungleLeaves = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Grass", Value=8)]
      Grass = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Stone", Value=9)]
      Stone = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BedRock", Value=10)]
      BedRock = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poppy", Value=11)]
      Poppy = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Dandelion", Value=12)]
      Dandelion = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OakLog", Value=13)]
      OakLog = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OakLeaves", Value=14)]
      OakLeaves = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BrickStairs", Value=15)]
      BrickStairs = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Torch", Value=16)]
      Torch = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BrickWall", Value=17)]
      BrickWall = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OakPlanks", Value=18)]
      OakPlanks = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DoubleStoneSlab", Value=19)]
      DoubleStoneSlab = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Cobweb", Value=20)]
      Cobweb = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RedSand", Value=21)]
      RedSand = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OakSapling", Value=22)]
      OakSapling = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CoalOre", Value=23)]
      CoalOre = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IronOre", Value=24)]
      IronOre = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GoldOre", Value=25)]
      GoldOre = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DiamondOre", Value=26)]
      DiamondOre = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EmeraldOre", Value=27)]
      EmeraldOre = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RedstoneOre", Value=28)]
      RedstoneOre = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CoalBlock", Value=29)]
      CoalBlock = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IronBlock", Value=30)]
      IronBlock = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GoldBlock", Value=31)]
      GoldBlock = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DiamondBlock", Value=32)]
      DiamondBlock = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EmeraldBlock", Value=33)]
      EmeraldBlock = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RedstoneBlock", Value=34)]
      RedstoneBlock = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Sand", Value=35)]
      Sand = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Gravel", Value=36)]
      Gravel = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OakWoodStairs", Value=37)]
      OakWoodStairs = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CobblestoneStairs", Value=38)]
      CobblestoneStairs = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StoneBrickStairs", Value=39)]
      StoneBrickStairs = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NetherBrickStairs", Value=40)]
      NetherBrickStairs = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SandstoneStairs", Value=41)]
      SandstoneStairs = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpruceWoodStairs", Value=42)]
      SpruceWoodStairs = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BirchWoodStairs", Value=43)]
      BirchWoodStairs = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JungleWoodStairs", Value=44)]
      JungleWoodStairs = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuartzStairs", Value=45)]
      QuartzStairs = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpruceWoodPlanks", Value=46)]
      SpruceWoodPlanks = 46,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BirchWoodPlanks", Value=47)]
      BirchWoodPlanks = 47,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JungleWoodPlanks", Value=48)]
      JungleWoodPlanks = 48,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AcaciaWoodPlanks", Value=49)]
      AcaciaWoodPlanks = 49,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DarkOakWoodPlanks", Value=50)]
      DarkOakWoodPlanks = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Cobblestone", Value=51)]
      Cobblestone = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StoneBricks", Value=52)]
      StoneBricks = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CobblestoneWall", Value=53)]
      CobblestoneWall = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Bookshelf", Value=54)]
      Bookshelf = 54,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MossyCobblestoneWall", Value=55)]
      MossyCobblestoneWall = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MossyCobblestone", Value=56)]
      MossyCobblestone = 56,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MossyCobblestoneStairs", Value=57)]
      MossyCobblestoneStairs = 57,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MossyStoneBricks", Value=58)]
      MossyStoneBricks = 58,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MossyStoneBrickStairs", Value=59)]
      MossyStoneBrickStairs = 59,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MossyStoneBrickWall", Value=60)]
      MossyStoneBrickWall = 60,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OakSlab", Value=61)]
      OakSlab = 61,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpruceSlab", Value=62)]
      SpruceSlab = 62,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BirchSlab", Value=63)]
      BirchSlab = 63,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JungleSlab", Value=64)]
      JungleSlab = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AcaciaSlab", Value=65)]
      AcaciaSlab = 65,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DarkOakSlab", Value=66)]
      DarkOakSlab = 66,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StoneSlab", Value=67)]
      StoneSlab = 67,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SmoothStoneSlab", Value=68)]
      SmoothStoneSlab = 68,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CobblestoneSlab", Value=69)]
      CobblestoneSlab = 69,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MossyCobblestoneSlab", Value=70)]
      MossyCobblestoneSlab = 70,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StoneBrickSlab", Value=71)]
      StoneBrickSlab = 71,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MossyStoneBrickSlab", Value=72)]
      MossyStoneBrickSlab = 72,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BrickSlab", Value=73)]
      BrickSlab = 73,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NetherBrickSlab", Value=74)]
      NetherBrickSlab = 74,
            
      [global::ProtoBuf.ProtoEnum(Name=@"QuartzSlab", Value=75)]
      QuartzSlab = 75,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Glass", Value=76)]
      Glass = 76,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GlassPane", Value=77)]
      GlassPane = 77,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpruceLeaves", Value=78)]
      SpruceLeaves = 78,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BirchLeaves", Value=79)]
      BirchLeaves = 79,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AcaciaLeaves", Value=80)]
      AcaciaLeaves = 80,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DarkOakLeaves", Value=81)]
      DarkOakLeaves = 81,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BirchLog", Value=82)]
      BirchLog = 82,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpruceLog", Value=83)]
      SpruceLog = 83,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JungleLog", Value=84)]
      JungleLog = 84,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AcaciaLog", Value=85)]
      AcaciaLog = 85,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DarkOakLog", Value=86)]
      DarkOakLog = 86,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SpruceSapling", Value=87)]
      SpruceSapling = 87,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BirchSapling", Value=88)]
      BirchSapling = 88,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JungleSapling", Value=89)]
      JungleSapling = 89,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AcaciaSapling", Value=90)]
      AcaciaSapling = 90,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DarkOakSapling", Value=91)]
      DarkOakSapling = 91,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ice", Value=92)]
      Ice = 92,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PackedIce", Value=93)]
      PackedIce = 93,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Chest", Value=94)]
      Chest = 94,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VerticalBrickSlab", Value=95)]
      VerticalBrickSlab = 95,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeadBush", Value=96)]
      DeadBush = 96,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Cactus", Value=97)]
      Cactus = 97
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CSBlockOrientation")]
    public enum CSBlockOrientation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Default", Value=0)]
      Default = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PositiveY_PositiveZ", Value=1)]
      PositiveY_PositiveZ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PositiveY_PositiveX", Value=2)]
      PositiveY_PositiveX = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PositiveY_NegativeZ", Value=3)]
      PositiveY_NegativeZ = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PositiveY_NegativeX", Value=4)]
      PositiveY_NegativeX = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NegativeY_PositiveZ", Value=5)]
      NegativeY_PositiveZ = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NegativeY_PositiveX", Value=6)]
      NegativeY_PositiveX = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NegativeY_NegativeZ", Value=7)]
      NegativeY_NegativeZ = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NegativeY_NegativeX", Value=8)]
      NegativeY_NegativeX = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"X", Value=9)]
      X = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Y", Value=10)]
      Y = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Z", Value=11)]
      Z = 11
    }
  
}