---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by roshan.
--- DateTime: 2018/11/18 9:56
---

testlua = {}
this = testlua

function this.Awake()
    print("Gameobject name = "..tostring(this.gameObject.name))
end

function this.Start()
    
end

function this.Destroy()
    
end

function this.Update()
    
end

